### ISSUE TITLE
Make the UI for profile/settings (mobile)

### ISSUE THREAD

**Issue by nashirj** [COP4331-LargeGroupProject-Fall22/mobile-app#7]
- [x] Sign out button?
- [x] Update profile info button
- [x] Update password button
- [ ] Profile image
- [x] First name
- [x] Last name
- [x] Email
- [x] Tab bar at bottom that takes you back to ingredients/recipe/shopping cart page (not hooked up yet)
- [ ] User profile button top left (that does nothing?)

As with all UI issues, just the components, no server connection.

**Comment by smaliszewski15** [comment]
the user profile button in the top left was initially when that button wasnt in the buttom row. it will not be there anymore in prodution.
